I0222 13:23:51.443137 361243 init.cc:233] ENV [CUSTOM_DEVICE_ROOT]=/root/miniconda3/envs/bytetrack/lib/python3.10/site-packages/paddle_custom_device
I0222 13:23:51.443194 361243 init.cc:142] Try loading custom device libs from: [/root/miniconda3/envs/bytetrack/lib/python3.10/site-packages/paddle_custom_device]
sdaa plugin compiled with gcc
PaddlePaddle Compilation Commit: e5b01458d31bab831dbd96a53522bf207b2fcd9e
PaddlePaddle Compilation Version: 2.6.0
+---------+--------+---------------+--------------+-------------+----------+-----------+-----------+-------------+-------+---------------------+--------------------+
|         | paddle | paddle_commit | sdaa_runtime | sdaa_driver | teco_dnn | teco_blas | teco_tccl | teco_custom | sdpti | paddle_sdaa_version | paddle_sdaa_commit |
+---------+--------+---------------+--------------+-------------+----------+-----------+-----------+-------------+-------+---------------------+--------------------+
| Version | 2.6.0  | e5b0145       | 1.3.1        | 1.3.1       | 2.0.0b0  | 2.0.0b0   | 1.20.0    | 1.22.0      | 1.3.0 | 1.3.1               | 9671916            |
+---------+--------+---------------+--------------+-------------+----------+-----------+-----------+-------------+-------+---------------------+--------------------+
+--------------------------+---------------+---------------+
| Variable Name            | Default Value | Current Value |
+--------------------------+---------------+---------------+
| CUSTOM_DEVICE_BLACK_LIST |               |               |
+--------------------------+---------------+---------------+
| ENABLE_SDPTI             | 1             | 1             |
+--------------------------+---------------+---------------+
| HIGH_PERFORMANCE_CONV    | 0             | 0             |
+--------------------------+---------------+---------------+
| HIGH_PERFORMANCE_GEMM    | 0             | 0             |
+--------------------------+---------------+---------------+
| RANDOM_ALIGN_NV_DEVICE   |               |               |
+--------------------------+---------------+---------------+
| PADDLE_XCCL_BACKEND      |               | sdaa          |
+--------------------------+---------------+---------------+
| HIGH_PRECISION_OP_LIST   |               |               |
+--------------------------+---------------+---------------+
| FLAGS_sdaa_reuse_event   | true          | true          |
+--------------------------+---------------+---------------+
| FLAGS_sdaa_runtime_debug | false         | false         |
+--------------------------+---------------+---------------+
| FLAGS_sdaa_matmul_scale  | 1.0           | 1.0           |
+--------------------------+---------------+---------------+
| DUMP_INTO_PROFILER       | 0             | 0             |
+--------------------------+---------------+---------------+
I0222 13:23:51.520812 361243 custom_device.cc:1109] Successed in loading custom runtime in lib: /root/miniconda3/envs/bytetrack/lib/python3.10/site-packages/paddle_custom_device/libpaddle-sdaa.so
I0222 13:23:51.522722 361243 custom_kernel.cc:63] Successed in loading 271 custom kernel(s) from loaded lib(s), will be used like native ones.
I0222 13:23:51.522811 361243 init.cc:154] Finished in LoadCustomDevice with libs_path: [/root/miniconda3/envs/bytetrack/lib/python3.10/site-packages/paddle_custom_device]
I0222 13:23:51.522830 361243 init.cc:239] CustomDevice: sdaa, visible devices count: 1
Warning: Unable to use JDE/FairMOT/ByteTrack, please install lap, for example: `pip install lap`, see https://github.com/gatagat/lap
Warning: Unable to use numba in PP-Tracking, please install numba, for example(python3.7): `pip install numba==0.56.4`
2025-02-22 13:23:52,627 - DEBUG - matplotlib data path: /root/miniconda3/envs/bytetrack/lib/python3.10/site-packages/matplotlib/mpl-data
2025-02-22 13:23:52,631 - DEBUG - CONFIGDIR=/root/.config/matplotlib
2025-02-22 13:23:52,633 - DEBUG - interactive is False
2025-02-22 13:23:52,633 - DEBUG - platform is linux
2025-02-22 13:23:52,683 - DEBUG - CACHEDIR=/root/.cache/matplotlib
2025-02-22 13:23:52,684 - DEBUG - Using fontManager instance from /root/.cache/matplotlib/fontlist-v390.json
Warning: Unable to use numba in PP-Tracking, please install numba, for example(python3.7): `pip install numba==0.56.4`
Warning: Unable to use MOT metric, please install motmetrics, for example: `pip install motmetrics`, see https://github.com/longcw/py-motmetrics
Warning: Unable to use MCMOT metric, please install motmetrics, for example: `pip install motmetrics`, see https://github.com/longcw/py-motmetrics
Warning: import ppdet from source directory without installing, run 'python setup.py install' to install ppdet firstly
I0222 13:23:53.307873 361243 tcp_utils.cc:107] Retry to connect to 172.17.0.3:47006 while the server is not yet listening.
I0222 13:23:56.308145 361243 tcp_utils.cc:130] Successfully connected to 172.17.0.3:47006
Traceback (most recent call last):
  File "/root/cas/tww/PaddleDetection-release-2.8/tools/train.py", line 230, in <module>
    main()
  File "/root/cas/tww/PaddleDetection-release-2.8/tools/train.py", line 226, in main
    run(FLAGS, cfg)
  File "/root/cas/tww/PaddleDetection-release-2.8/tools/train.py", line 166, in run
    trainer = Trainer(cfg, mode='train')
  File "/root/cas/tww/PaddleDetection-release-2.8/ppdet/engine/trainer.py", line 125, in __init__
    self.loader = create('{}Reader'.format(capital_mode))(
  File "/root/cas/tww/PaddleDetection-release-2.8/ppdet/data/reader.py", line 190, in __call__
    self.dataset.parse_dataset()
  File "/root/cas/tww/PaddleDetection-release-2.8/ppdet/data/source/mot.py", line 116, in parse_dataset
    assert os.path.isdir(image_lists_dir), \
AssertionError: The dataset/mot/image_lists is not a directory.
I0222 13:46:27.420480 363174 init.cc:233] ENV [CUSTOM_DEVICE_ROOT]=/root/miniconda3/envs/bytetrack/lib/python3.10/site-packages/paddle_custom_device
I0222 13:46:27.420544 363174 init.cc:142] Try loading custom device libs from: [/root/miniconda3/envs/bytetrack/lib/python3.10/site-packages/paddle_custom_device]
sdaa plugin compiled with gcc
PaddlePaddle Compilation Commit: e5b01458d31bab831dbd96a53522bf207b2fcd9e
PaddlePaddle Compilation Version: 2.6.0
+---------+--------+---------------+--------------+-------------+----------+-----------+-----------+-------------+-------+---------------------+--------------------+
|         | paddle | paddle_commit | sdaa_runtime | sdaa_driver | teco_dnn | teco_blas | teco_tccl | teco_custom | sdpti | paddle_sdaa_version | paddle_sdaa_commit |
+---------+--------+---------------+--------------+-------------+----------+-----------+-----------+-------------+-------+---------------------+--------------------+
| Version | 2.6.0  | e5b0145       | 1.3.1        | 1.3.1       | 2.0.0b0  | 2.0.0b0   | 1.20.0    | 1.22.0      | 1.3.0 | 1.3.1               | 9671916            |
+---------+--------+---------------+--------------+-------------+----------+-----------+-----------+-------------+-------+---------------------+--------------------+
+--------------------------+---------------+---------------+
| Variable Name            | Default Value | Current Value |
+--------------------------+---------------+---------------+
| CUSTOM_DEVICE_BLACK_LIST |               |               |
+--------------------------+---------------+---------------+
| ENABLE_SDPTI             | 1             | 1             |
+--------------------------+---------------+---------------+
| HIGH_PERFORMANCE_CONV    | 0             | 0             |
+--------------------------+---------------+---------------+
| HIGH_PERFORMANCE_GEMM    | 0             | 0             |
+--------------------------+---------------+---------------+
| RANDOM_ALIGN_NV_DEVICE   |               |               |
+--------------------------+---------------+---------------+
| PADDLE_XCCL_BACKEND      |               | sdaa          |
+--------------------------+---------------+---------------+
| HIGH_PRECISION_OP_LIST   |               |               |
+--------------------------+---------------+---------------+
| FLAGS_sdaa_reuse_event   | true          | true          |
+--------------------------+---------------+---------------+
| FLAGS_sdaa_runtime_debug | false         | false         |
+--------------------------+---------------+---------------+
| FLAGS_sdaa_matmul_scale  | 1.0           | 1.0           |
+--------------------------+---------------+---------------+
| DUMP_INTO_PROFILER       | 0             | 0             |
+--------------------------+---------------+---------------+
I0222 13:46:27.520463 363174 custom_device.cc:1109] Successed in loading custom runtime in lib: /root/miniconda3/envs/bytetrack/lib/python3.10/site-packages/paddle_custom_device/libpaddle-sdaa.so
I0222 13:46:27.522923 363174 custom_kernel.cc:63] Successed in loading 271 custom kernel(s) from loaded lib(s), will be used like native ones.
I0222 13:46:27.523041 363174 init.cc:154] Finished in LoadCustomDevice with libs_path: [/root/miniconda3/envs/bytetrack/lib/python3.10/site-packages/paddle_custom_device]
I0222 13:46:27.523082 363174 init.cc:239] CustomDevice: sdaa, visible devices count: 1
Warning: Unable to use JDE/FairMOT/ByteTrack, please install lap, for example: `pip install lap`, see https://github.com/gatagat/lap
Warning: Unable to use numba in PP-Tracking, please install numba, for example(python3.7): `pip install numba==0.56.4`
2025-02-22 13:46:28,332 - DEBUG - matplotlib data path: /root/miniconda3/envs/bytetrack/lib/python3.10/site-packages/matplotlib/mpl-data
2025-02-22 13:46:28,336 - DEBUG - CONFIGDIR=/root/.config/matplotlib
2025-02-22 13:46:28,337 - DEBUG - interactive is False
2025-02-22 13:46:28,337 - DEBUG - platform is linux
2025-02-22 13:46:28,382 - DEBUG - CACHEDIR=/root/.cache/matplotlib
2025-02-22 13:46:28,383 - DEBUG - Using fontManager instance from /root/.cache/matplotlib/fontlist-v390.json
Warning: Unable to use numba in PP-Tracking, please install numba, for example(python3.7): `pip install numba==0.56.4`
Warning: Unable to use MOT metric, please install motmetrics, for example: `pip install motmetrics`, see https://github.com/longcw/py-motmetrics
Warning: Unable to use MCMOT metric, please install motmetrics, for example: `pip install motmetrics`, see https://github.com/longcw/py-motmetrics
Warning: import ppdet from source directory without installing, run 'python setup.py install' to install ppdet firstly
I0222 13:46:28.815716 363174 tcp_utils.cc:107] Retry to connect to 172.17.0.3:37797 while the server is not yet listening.
I0222 13:46:31.815925 363174 tcp_utils.cc:130] Successfully connected to 172.17.0.3:37797
Traceback (most recent call last):
  File "/root/cas/tww/PaddleDetection-release-2.8/tools/train.py", line 230, in <module>
    main()
  File "/root/cas/tww/PaddleDetection-release-2.8/tools/train.py", line 226, in main
    run(FLAGS, cfg)
  File "/root/cas/tww/PaddleDetection-release-2.8/tools/train.py", line 166, in run
    trainer = Trainer(cfg, mode='train')
  File "/root/cas/tww/PaddleDetection-release-2.8/ppdet/engine/trainer.py", line 125, in __init__
    self.loader = create('{}Reader'.format(capital_mode))(
  File "/root/cas/tww/PaddleDetection-release-2.8/ppdet/data/reader.py", line 190, in __call__
    self.dataset.parse_dataset()
  File "/root/cas/tww/PaddleDetection-release-2.8/ppdet/data/source/mot.py", line 120, in parse_dataset
    assert os.path.exists(list_path), \
AssertionError: The list path dataset/mot/image_lists/caltech.all does not exist.
I0222 13:49:38.192333 363488 init.cc:233] ENV [CUSTOM_DEVICE_ROOT]=/root/miniconda3/envs/bytetrack/lib/python3.10/site-packages/paddle_custom_device
I0222 13:49:38.192389 363488 init.cc:142] Try loading custom device libs from: [/root/miniconda3/envs/bytetrack/lib/python3.10/site-packages/paddle_custom_device]
sdaa plugin compiled with gcc
PaddlePaddle Compilation Commit: e5b01458d31bab831dbd96a53522bf207b2fcd9e
PaddlePaddle Compilation Version: 2.6.0
+---------+--------+---------------+--------------+-------------+----------+-----------+-----------+-------------+-------+---------------------+--------------------+
|         | paddle | paddle_commit | sdaa_runtime | sdaa_driver | teco_dnn | teco_blas | teco_tccl | teco_custom | sdpti | paddle_sdaa_version | paddle_sdaa_commit |
+---------+--------+---------------+--------------+-------------+----------+-----------+-----------+-------------+-------+---------------------+--------------------+
| Version | 2.6.0  | e5b0145       | 1.3.1        | 1.3.1       | 2.0.0b0  | 2.0.0b0   | 1.20.0    | 1.22.0      | 1.3.0 | 1.3.1               | 9671916            |
+---------+--------+---------------+--------------+-------------+----------+-----------+-----------+-------------+-------+---------------------+--------------------+
+--------------------------+---------------+---------------+
| Variable Name            | Default Value | Current Value |
+--------------------------+---------------+---------------+
| CUSTOM_DEVICE_BLACK_LIST |               |               |
+--------------------------+---------------+---------------+
| ENABLE_SDPTI             | 1             | 1             |
+--------------------------+---------------+---------------+
| HIGH_PERFORMANCE_CONV    | 0             | 0             |
+--------------------------+---------------+---------------+
| HIGH_PERFORMANCE_GEMM    | 0             | 0             |
+--------------------------+---------------+---------------+
| RANDOM_ALIGN_NV_DEVICE   |               |               |
+--------------------------+---------------+---------------+
| PADDLE_XCCL_BACKEND      |               | sdaa          |
+--------------------------+---------------+---------------+
| HIGH_PRECISION_OP_LIST   |               |               |
+--------------------------+---------------+---------------+
| FLAGS_sdaa_reuse_event   | true          | true          |
+--------------------------+---------------+---------------+
| FLAGS_sdaa_runtime_debug | false         | false         |
+--------------------------+---------------+---------------+
| FLAGS_sdaa_matmul_scale  | 1.0           | 1.0           |
+--------------------------+---------------+---------------+
| DUMP_INTO_PROFILER       | 0             | 0             |
+--------------------------+---------------+---------------+
I0222 13:49:38.292335 363488 custom_device.cc:1109] Successed in loading custom runtime in lib: /root/miniconda3/envs/bytetrack/lib/python3.10/site-packages/paddle_custom_device/libpaddle-sdaa.so
I0222 13:49:38.294891 363488 custom_kernel.cc:63] Successed in loading 271 custom kernel(s) from loaded lib(s), will be used like native ones.
I0222 13:49:38.295017 363488 init.cc:154] Finished in LoadCustomDevice with libs_path: [/root/miniconda3/envs/bytetrack/lib/python3.10/site-packages/paddle_custom_device]
I0222 13:49:38.295043 363488 init.cc:239] CustomDevice: sdaa, visible devices count: 1
Warning: Unable to use JDE/FairMOT/ByteTrack, please install lap, for example: `pip install lap`, see https://github.com/gatagat/lap
Warning: Unable to use numba in PP-Tracking, please install numba, for example(python3.7): `pip install numba==0.56.4`
2025-02-22 13:49:39,234 - DEBUG - matplotlib data path: /root/miniconda3/envs/bytetrack/lib/python3.10/site-packages/matplotlib/mpl-data
2025-02-22 13:49:39,240 - DEBUG - CONFIGDIR=/root/.config/matplotlib
2025-02-22 13:49:39,242 - DEBUG - interactive is False
2025-02-22 13:49:39,242 - DEBUG - platform is linux
2025-02-22 13:49:39,298 - DEBUG - CACHEDIR=/root/.cache/matplotlib
2025-02-22 13:49:39,300 - DEBUG - Using fontManager instance from /root/.cache/matplotlib/fontlist-v390.json
Warning: Unable to use numba in PP-Tracking, please install numba, for example(python3.7): `pip install numba==0.56.4`
Warning: Unable to use MOT metric, please install motmetrics, for example: `pip install motmetrics`, see https://github.com/longcw/py-motmetrics
Warning: Unable to use MCMOT metric, please install motmetrics, for example: `pip install motmetrics`, see https://github.com/longcw/py-motmetrics
Warning: import ppdet from source directory without installing, run 'python setup.py install' to install ppdet firstly
I0222 13:49:39.795002 363488 tcp_utils.cc:130] Successfully connected to 172.17.0.3:52483
Traceback (most recent call last):
  File "/root/cas/tww/PaddleDetection-release-2.8/tools/train.py", line 230, in <module>
    main()
  File "/root/cas/tww/PaddleDetection-release-2.8/tools/train.py", line 226, in main
    run(FLAGS, cfg)
  File "/root/cas/tww/PaddleDetection-release-2.8/tools/train.py", line 166, in run
    trainer = Trainer(cfg, mode='train')
  File "/root/cas/tww/PaddleDetection-release-2.8/ppdet/engine/trainer.py", line 125, in __init__
    self.loader = create('{}Reader'.format(capital_mode))(
  File "/root/cas/tww/PaddleDetection-release-2.8/ppdet/data/reader.py", line 190, in __call__
    self.dataset.parse_dataset()
  File "/root/cas/tww/PaddleDetection-release-2.8/ppdet/data/source/mot.py", line 120, in parse_dataset
    assert os.path.exists(list_path), \
AssertionError: The list path dataset/mot/image_lists/caltech.all does not exist.
I0222 13:55:37.134492 363970 init.cc:233] ENV [CUSTOM_DEVICE_ROOT]=/root/miniconda3/envs/bytetrack/lib/python3.10/site-packages/paddle_custom_device
I0222 13:55:37.134562 363970 init.cc:142] Try loading custom device libs from: [/root/miniconda3/envs/bytetrack/lib/python3.10/site-packages/paddle_custom_device]
sdaa plugin compiled with gcc
PaddlePaddle Compilation Commit: e5b01458d31bab831dbd96a53522bf207b2fcd9e
PaddlePaddle Compilation Version: 2.6.0
+---------+--------+---------------+--------------+-------------+----------+-----------+-----------+-------------+-------+---------------------+--------------------+
|         | paddle | paddle_commit | sdaa_runtime | sdaa_driver | teco_dnn | teco_blas | teco_tccl | teco_custom | sdpti | paddle_sdaa_version | paddle_sdaa_commit |
+---------+--------+---------------+--------------+-------------+----------+-----------+-----------+-------------+-------+---------------------+--------------------+
| Version | 2.6.0  | e5b0145       | 1.3.1        | 1.3.1       | 2.0.0b0  | 2.0.0b0   | 1.20.0    | 1.22.0      | 1.3.0 | 1.3.1               | 9671916            |
+---------+--------+---------------+--------------+-------------+----------+-----------+-----------+-------------+-------+---------------------+--------------------+
+--------------------------+---------------+---------------+
| Variable Name            | Default Value | Current Value |
+--------------------------+---------------+---------------+
| CUSTOM_DEVICE_BLACK_LIST |               |               |
+--------------------------+---------------+---------------+
| ENABLE_SDPTI             | 1             | 1             |
+--------------------------+---------------+---------------+
| HIGH_PERFORMANCE_CONV    | 0             | 0             |
+--------------------------+---------------+---------------+
| HIGH_PERFORMANCE_GEMM    | 0             | 0             |
+--------------------------+---------------+---------------+
| RANDOM_ALIGN_NV_DEVICE   |               |               |
+--------------------------+---------------+---------------+
| PADDLE_XCCL_BACKEND      |               | sdaa          |
+--------------------------+---------------+---------------+
| HIGH_PRECISION_OP_LIST   |               |               |
+--------------------------+---------------+---------------+
| FLAGS_sdaa_reuse_event   | true          | true          |
+--------------------------+---------------+---------------+
| FLAGS_sdaa_runtime_debug | false         | false         |
+--------------------------+---------------+---------------+
| FLAGS_sdaa_matmul_scale  | 1.0           | 1.0           |
+--------------------------+---------------+---------------+
| DUMP_INTO_PROFILER       | 0             | 0             |
+--------------------------+---------------+---------------+
I0222 13:55:37.232935 363970 custom_device.cc:1109] Successed in loading custom runtime in lib: /root/miniconda3/envs/bytetrack/lib/python3.10/site-packages/paddle_custom_device/libpaddle-sdaa.so
I0222 13:55:37.235455 363970 custom_kernel.cc:63] Successed in loading 271 custom kernel(s) from loaded lib(s), will be used like native ones.
I0222 13:55:37.235579 363970 init.cc:154] Finished in LoadCustomDevice with libs_path: [/root/miniconda3/envs/bytetrack/lib/python3.10/site-packages/paddle_custom_device]
I0222 13:55:37.235615 363970 init.cc:239] CustomDevice: sdaa, visible devices count: 1
Warning: Unable to use JDE/FairMOT/ByteTrack, please install lap, for example: `pip install lap`, see https://github.com/gatagat/lap
Warning: Unable to use numba in PP-Tracking, please install numba, for example(python3.7): `pip install numba==0.56.4`
2025-02-22 13:55:38,129 - DEBUG - matplotlib data path: /root/miniconda3/envs/bytetrack/lib/python3.10/site-packages/matplotlib/mpl-data
2025-02-22 13:55:38,133 - DEBUG - CONFIGDIR=/root/.config/matplotlib
2025-02-22 13:55:38,135 - DEBUG - interactive is False
2025-02-22 13:55:38,135 - DEBUG - platform is linux
2025-02-22 13:55:38,180 - DEBUG - CACHEDIR=/root/.cache/matplotlib
2025-02-22 13:55:38,180 - DEBUG - Using fontManager instance from /root/.cache/matplotlib/fontlist-v390.json
Warning: Unable to use numba in PP-Tracking, please install numba, for example(python3.7): `pip install numba==0.56.4`
Warning: Unable to use MOT metric, please install motmetrics, for example: `pip install motmetrics`, see https://github.com/longcw/py-motmetrics
Warning: Unable to use MCMOT metric, please install motmetrics, for example: `pip install motmetrics`, see https://github.com/longcw/py-motmetrics
Warning: import ppdet from source directory without installing, run 'python setup.py install' to install ppdet firstly
I0222 13:55:38.605975 363970 tcp_utils.cc:130] Successfully connected to 172.17.0.3:50942
2025-02-22 14:00:25,071 - INFO - Loss: 10.6583
2025-02-22 14:04:54,808 - INFO - Loss: 10.2613
2025-02-22 14:09:25,452 - INFO - Loss: 9.3819


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   egr::Backward(std::vector<paddle::Tensor, std::allocator<paddle::Tensor> > const&, std::vector<paddle::Tensor, std::allocator<paddle::Tensor> > const&, bool)
1   egr::RunBackward(std::vector<paddle::Tensor, std::allocator<paddle::Tensor> > const&, std::vector<paddle::Tensor, std::allocator<paddle::Tensor> > const&, bool, bool, std::vector<paddle::Tensor, std::allocator<paddle::Tensor> > const&, bool, std::vector<paddle::Tensor, std::allocator<paddle::Tensor> > const&)
2   DeformableConvGradNode::operator()(paddle::small_vector<std::vector<paddle::Tensor, std::allocator<paddle::Tensor> >, 15u>&, bool, bool)
3   paddle::experimental::deformable_conv_grad(paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::optional<paddle::Tensor> const&, paddle::Tensor const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, int, int, int, paddle::Tensor*, paddle::Tensor*, paddle::Tensor*, paddle::Tensor*)
4   void phi::DeformableConvGradKernel<float, phi::CPUContext>(phi::CPUContext const&, phi::DenseTensor const&, phi::DenseTensor const&, phi::DenseTensor const&, paddle::optional<phi::DenseTensor> const&, phi::DenseTensor const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, int, int, int, phi::DenseTensor*, phi::DenseTensor*, phi::DenseTensor*, phi::DenseTensor*)
5   void phi::ModulatedDeformableCol2im<float, phi::CPUContext>(phi::CPUContext const&, float const*, float const*, float const*, std::vector<long, std::allocator<long> > const&, std::vector<long, std::allocator<long> > const&, std::vector<long, std::allocator<long> > const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, int, float*)

----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1740233480 (unix time) try "date -d @1740233480" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x58d6e) received by PID 363970 (TID 0x7f6e7b10d740) from PID 363886 ***]

I0222 14:12:38.180820 371428 init.cc:233] ENV [CUSTOM_DEVICE_ROOT]=/root/miniconda3/envs/bytetrack/lib/python3.10/site-packages/paddle_custom_device
I0222 14:12:38.180866 371428 init.cc:142] Try loading custom device libs from: [/root/miniconda3/envs/bytetrack/lib/python3.10/site-packages/paddle_custom_device]
sdaa plugin compiled with gcc
PaddlePaddle Compilation Commit: e5b01458d31bab831dbd96a53522bf207b2fcd9e
PaddlePaddle Compilation Version: 2.6.0
+---------+--------+---------------+--------------+-------------+----------+-----------+-----------+-------------+-------+---------------------+--------------------+
|         | paddle | paddle_commit | sdaa_runtime | sdaa_driver | teco_dnn | teco_blas | teco_tccl | teco_custom | sdpti | paddle_sdaa_version | paddle_sdaa_commit |
+---------+--------+---------------+--------------+-------------+----------+-----------+-----------+-------------+-------+---------------------+--------------------+
| Version | 2.6.0  | e5b0145       | 1.3.1        | 1.3.1       | 2.0.0b0  | 2.0.0b0   | 1.20.0    | 1.22.0      | 1.3.0 | 1.3.1               | 9671916            |
+---------+--------+---------------+--------------+-------------+----------+-----------+-----------+-------------+-------+---------------------+--------------------+
+--------------------------+---------------+---------------+
| Variable Name            | Default Value | Current Value |
+--------------------------+---------------+---------------+
| CUSTOM_DEVICE_BLACK_LIST |               |               |
+--------------------------+---------------+---------------+
| ENABLE_SDPTI             | 1             | 1             |
+--------------------------+---------------+---------------+
| HIGH_PERFORMANCE_CONV    | 0             | 0             |
+--------------------------+---------------+---------------+
| HIGH_PERFORMANCE_GEMM    | 0             | 0             |
+--------------------------+---------------+---------------+
| RANDOM_ALIGN_NV_DEVICE   |               |               |
+--------------------------+---------------+---------------+
| PADDLE_XCCL_BACKEND      |               | sdaa          |
+--------------------------+---------------+---------------+
| HIGH_PRECISION_OP_LIST   |               |               |
+--------------------------+---------------+---------------+
| FLAGS_sdaa_reuse_event   | true          | true          |
+--------------------------+---------------+---------------+
| FLAGS_sdaa_runtime_debug | false         | false         |
+--------------------------+---------------+---------------+
| FLAGS_sdaa_matmul_scale  | 1.0           | 1.0           |
+--------------------------+---------------+---------------+
| DUMP_INTO_PROFILER       | 0             | 0             |
+--------------------------+---------------+---------------+
I0222 14:12:38.258862 371428 custom_device.cc:1109] Successed in loading custom runtime in lib: /root/miniconda3/envs/bytetrack/lib/python3.10/site-packages/paddle_custom_device/libpaddle-sdaa.so
I0222 14:12:38.260769 371428 custom_kernel.cc:63] Successed in loading 271 custom kernel(s) from loaded lib(s), will be used like native ones.
I0222 14:12:38.260859 371428 init.cc:154] Finished in LoadCustomDevice with libs_path: [/root/miniconda3/envs/bytetrack/lib/python3.10/site-packages/paddle_custom_device]
I0222 14:12:38.260875 371428 init.cc:239] CustomDevice: sdaa, visible devices count: 1
Warning: Unable to use JDE/FairMOT/ByteTrack, please install lap, for example: `pip install lap`, see https://github.com/gatagat/lap
Warning: Unable to use numba in PP-Tracking, please install numba, for example(python3.7): `pip install numba==0.56.4`
2025-02-22 14:12:39,086 - DEBUG - matplotlib data path: /root/miniconda3/envs/bytetrack/lib/python3.10/site-packages/matplotlib/mpl-data
2025-02-22 14:12:39,091 - DEBUG - CONFIGDIR=/root/.config/matplotlib
2025-02-22 14:12:39,092 - DEBUG - interactive is False
2025-02-22 14:12:39,092 - DEBUG - platform is linux
2025-02-22 14:12:39,152 - DEBUG - CACHEDIR=/root/.cache/matplotlib
2025-02-22 14:12:39,153 - DEBUG - Using fontManager instance from /root/.cache/matplotlib/fontlist-v390.json
Warning: Unable to use numba in PP-Tracking, please install numba, for example(python3.7): `pip install numba==0.56.4`
Warning: Unable to use MOT metric, please install motmetrics, for example: `pip install motmetrics`, see https://github.com/longcw/py-motmetrics
Warning: Unable to use MCMOT metric, please install motmetrics, for example: `pip install motmetrics`, see https://github.com/longcw/py-motmetrics
Warning: import ppdet from source directory without installing, run 'python setup.py install' to install ppdet firstly
I0222 14:12:39.676921 371428 tcp_utils.cc:130] Successfully connected to 172.17.0.3:58768


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1740233561 (unix time) try "date -d @1740233561" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x5aa8e) received by PID 371428 (TID 0x7f978d843740) from PID 371342 ***]

I0222 14:12:50.115381 371814 init.cc:233] ENV [CUSTOM_DEVICE_ROOT]=/root/miniconda3/envs/bytetrack/lib/python3.10/site-packages/paddle_custom_device
I0222 14:12:50.115432 371814 init.cc:142] Try loading custom device libs from: [/root/miniconda3/envs/bytetrack/lib/python3.10/site-packages/paddle_custom_device]
sdaa plugin compiled with gcc
PaddlePaddle Compilation Commit: e5b01458d31bab831dbd96a53522bf207b2fcd9e
PaddlePaddle Compilation Version: 2.6.0
+---------+--------+---------------+--------------+-------------+----------+-----------+-----------+-------------+-------+---------------------+--------------------+
|         | paddle | paddle_commit | sdaa_runtime | sdaa_driver | teco_dnn | teco_blas | teco_tccl | teco_custom | sdpti | paddle_sdaa_version | paddle_sdaa_commit |
+---------+--------+---------------+--------------+-------------+----------+-----------+-----------+-------------+-------+---------------------+--------------------+
| Version | 2.6.0  | e5b0145       | 1.3.1        | 1.3.1       | 2.0.0b0  | 2.0.0b0   | 1.20.0    | 1.22.0      | 1.3.0 | 1.3.1               | 9671916            |
+---------+--------+---------------+--------------+-------------+----------+-----------+-----------+-------------+-------+---------------------+--------------------+
+--------------------------+---------------+---------------+
| Variable Name            | Default Value | Current Value |
+--------------------------+---------------+---------------+
| CUSTOM_DEVICE_BLACK_LIST |               |               |
+--------------------------+---------------+---------------+
| ENABLE_SDPTI             | 1             | 1             |
+--------------------------+---------------+---------------+
| HIGH_PERFORMANCE_CONV    | 0             | 0             |
+--------------------------+---------------+---------------+
| HIGH_PERFORMANCE_GEMM    | 0             | 0             |
+--------------------------+---------------+---------------+
| RANDOM_ALIGN_NV_DEVICE   |               |               |
+--------------------------+---------------+---------------+
| PADDLE_XCCL_BACKEND      |               | sdaa          |
+--------------------------+---------------+---------------+
| HIGH_PRECISION_OP_LIST   |               |               |
+--------------------------+---------------+---------------+
| FLAGS_sdaa_reuse_event   | true          | true          |
+--------------------------+---------------+---------------+
| FLAGS_sdaa_runtime_debug | false         | false         |
+--------------------------+---------------+---------------+
| FLAGS_sdaa_matmul_scale  | 1.0           | 1.0           |
+--------------------------+---------------+---------------+
| DUMP_INTO_PROFILER       | 0             | 0             |
+--------------------------+---------------+---------------+
I0222 14:12:50.194309 371814 custom_device.cc:1109] Successed in loading custom runtime in lib: /root/miniconda3/envs/bytetrack/lib/python3.10/site-packages/paddle_custom_device/libpaddle-sdaa.so
I0222 14:12:50.196218 371814 custom_kernel.cc:63] Successed in loading 271 custom kernel(s) from loaded lib(s), will be used like native ones.
I0222 14:12:50.196306 371814 init.cc:154] Finished in LoadCustomDevice with libs_path: [/root/miniconda3/envs/bytetrack/lib/python3.10/site-packages/paddle_custom_device]
I0222 14:12:50.196324 371814 init.cc:239] CustomDevice: sdaa, visible devices count: 1
Warning: Unable to use JDE/FairMOT/ByteTrack, please install lap, for example: `pip install lap`, see https://github.com/gatagat/lap
Warning: Unable to use numba in PP-Tracking, please install numba, for example(python3.7): `pip install numba==0.56.4`
2025-02-22 14:12:51,022 - DEBUG - matplotlib data path: /root/miniconda3/envs/bytetrack/lib/python3.10/site-packages/matplotlib/mpl-data
2025-02-22 14:12:51,027 - DEBUG - CONFIGDIR=/root/.config/matplotlib
2025-02-22 14:12:51,028 - DEBUG - interactive is False
2025-02-22 14:12:51,028 - DEBUG - platform is linux
2025-02-22 14:12:51,086 - DEBUG - CACHEDIR=/root/.cache/matplotlib
2025-02-22 14:12:51,088 - DEBUG - Using fontManager instance from /root/.cache/matplotlib/fontlist-v390.json
Warning: Unable to use numba in PP-Tracking, please install numba, for example(python3.7): `pip install numba==0.56.4`
Warning: Unable to use MOT metric, please install motmetrics, for example: `pip install motmetrics`, see https://github.com/longcw/py-motmetrics
Warning: Unable to use MCMOT metric, please install motmetrics, for example: `pip install motmetrics`, see https://github.com/longcw/py-motmetrics
Warning: import ppdet from source directory without installing, run 'python setup.py install' to install ppdet firstly
I0222 14:12:51.604800 371814 tcp_utils.cc:107] Retry to connect to 172.17.0.3:46069 while the server is not yet listening.


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   phi::distributed::CreateOrGetGlobalTCPStore()
1   phi::distributed::TCPStore::TCPStore(std::string, unsigned short, bool, unsigned long, int)
2   phi::distributed::detail::TCPClient::connect(std::string, unsigned short)
3   phi::distributed::tcputils::tcp_connect(std::string, std::string, int, std::chrono::duration<long, std::ratio<1l, 1l> >)

----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1740233573 (unix time) try "date -d @1740233573" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x5ac1a) received by PID 371814 (TID 0x7fbac0c49740) from PID 371738 ***]

I0222 14:13:23.862219 372349 init.cc:233] ENV [CUSTOM_DEVICE_ROOT]=/root/miniconda3/envs/bytetrack/lib/python3.10/site-packages/paddle_custom_device
I0222 14:13:23.862264 372349 init.cc:142] Try loading custom device libs from: [/root/miniconda3/envs/bytetrack/lib/python3.10/site-packages/paddle_custom_device]
sdaa plugin compiled with gcc
PaddlePaddle Compilation Commit: e5b01458d31bab831dbd96a53522bf207b2fcd9e
PaddlePaddle Compilation Version: 2.6.0
+---------+--------+---------------+--------------+-------------+----------+-----------+-----------+-------------+-------+---------------------+--------------------+
|         | paddle | paddle_commit | sdaa_runtime | sdaa_driver | teco_dnn | teco_blas | teco_tccl | teco_custom | sdpti | paddle_sdaa_version | paddle_sdaa_commit |
+---------+--------+---------------+--------------+-------------+----------+-----------+-----------+-------------+-------+---------------------+--------------------+
| Version | 2.6.0  | e5b0145       | 1.3.1        | 1.3.1       | 2.0.0b0  | 2.0.0b0   | 1.20.0    | 1.22.0      | 1.3.0 | 1.3.1               | 9671916            |
+---------+--------+---------------+--------------+-------------+----------+-----------+-----------+-------------+-------+---------------------+--------------------+
+--------------------------+---------------+---------------+
| Variable Name            | Default Value | Current Value |
+--------------------------+---------------+---------------+
| CUSTOM_DEVICE_BLACK_LIST |               |               |
+--------------------------+---------------+---------------+
| ENABLE_SDPTI             | 1             | 1             |
+--------------------------+---------------+---------------+
| HIGH_PERFORMANCE_CONV    | 0             | 0             |
+--------------------------+---------------+---------------+
| HIGH_PERFORMANCE_GEMM    | 0             | 0             |
+--------------------------+---------------+---------------+
| RANDOM_ALIGN_NV_DEVICE   |               |               |
+--------------------------+---------------+---------------+
| PADDLE_XCCL_BACKEND      |               | sdaa          |
+--------------------------+---------------+---------------+
| HIGH_PRECISION_OP_LIST   |               |               |
+--------------------------+---------------+---------------+
| FLAGS_sdaa_reuse_event   | true          | true          |
+--------------------------+---------------+---------------+
| FLAGS_sdaa_runtime_debug | false         | false         |
+--------------------------+---------------+---------------+
| FLAGS_sdaa_matmul_scale  | 1.0           | 1.0           |
+--------------------------+---------------+---------------+
| DUMP_INTO_PROFILER       | 0             | 0             |
+--------------------------+---------------+---------------+
I0222 14:13:23.930464 372349 custom_device.cc:1109] Successed in loading custom runtime in lib: /root/miniconda3/envs/bytetrack/lib/python3.10/site-packages/paddle_custom_device/libpaddle-sdaa.so
I0222 14:13:23.932190 372349 custom_kernel.cc:63] Successed in loading 271 custom kernel(s) from loaded lib(s), will be used like native ones.
I0222 14:13:23.932282 372349 init.cc:154] Finished in LoadCustomDevice with libs_path: [/root/miniconda3/envs/bytetrack/lib/python3.10/site-packages/paddle_custom_device]
I0222 14:13:23.932299 372349 init.cc:239] CustomDevice: sdaa, visible devices count: 1
Warning: Unable to use JDE/FairMOT/ByteTrack, please install lap, for example: `pip install lap`, see https://github.com/gatagat/lap
Warning: Unable to use numba in PP-Tracking, please install numba, for example(python3.7): `pip install numba==0.56.4`
2025-02-22 14:13:24,621 - DEBUG - matplotlib data path: /root/miniconda3/envs/bytetrack/lib/python3.10/site-packages/matplotlib/mpl-data
2025-02-22 14:13:24,625 - DEBUG - CONFIGDIR=/root/.config/matplotlib
2025-02-22 14:13:24,627 - DEBUG - interactive is False
2025-02-22 14:13:24,627 - DEBUG - platform is linux
2025-02-22 14:13:24,672 - DEBUG - CACHEDIR=/root/.cache/matplotlib
2025-02-22 14:13:24,673 - DEBUG - Using fontManager instance from /root/.cache/matplotlib/fontlist-v390.json
Warning: Unable to use numba in PP-Tracking, please install numba, for example(python3.7): `pip install numba==0.56.4`
Warning: Unable to use MOT metric, please install motmetrics, for example: `pip install motmetrics`, see https://github.com/longcw/py-motmetrics
Warning: Unable to use MCMOT metric, please install motmetrics, for example: `pip install motmetrics`, see https://github.com/longcw/py-motmetrics
Warning: import ppdet from source directory without installing, run 'python setup.py install' to install ppdet firstly
I0222 14:13:25.104185 372349 tcp_utils.cc:107] Retry to connect to 172.17.0.3:35642 while the server is not yet listening.
I0222 14:13:28.104391 372349 tcp_utils.cc:130] Successfully connected to 172.17.0.3:35642
2025-02-22 14:13:29,992 - DEBUG - Starting new HTTPS connection (1): paddledet.bj.bcebos.com:443
2025-02-22 14:13:30,135 - DEBUG - https://paddledet.bj.bcebos.com:443 "GET /models/mot/fairmot_dla34_30e_1088x608.pdparams HTTP/1.1" 200 130895015
2025-02-22 14:18:03,091 - INFO - Loss: 10.7535
2025-02-22 14:22:34,259 - INFO - Loss: 10.4191
2025-02-22 14:27:08,320 - INFO - Loss: 9.3337
2025-02-22 14:31:40,647 - INFO - Loss: 9.1136
2025-02-22 14:36:11,697 - INFO - Loss: 8.1540
2025-02-22 14:40:42,740 - INFO - Loss: 8.7241
2025-02-22 14:45:14,369 - INFO - Loss: 7.9623
2025-02-22 14:49:46,472 - INFO - Loss: 7.6762
2025-02-22 14:54:18,346 - INFO - Loss: 7.7411
2025-02-22 14:58:50,215 - INFO - Loss: 7.7818
2025-02-22 15:03:21,739 - INFO - Loss: 7.6103


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::pybind::eager_api_deformable_conv(_object*, _object*, _object*)
1   deformable_conv_ad_func(paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::optional<paddle::Tensor> const&, std::vector<int, std::allocator<int> >, std::vector<int, std::allocator<int> >, std::vector<int, std::allocator<int> >, int, int, int)
2   paddle::experimental::deformable_conv(paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::optional<paddle::Tensor> const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, int, int, int)
3   void phi::DeformableConvKernel<float, phi::CPUContext>(phi::CPUContext const&, phi::DenseTensor const&, phi::DenseTensor const&, phi::DenseTensor const&, paddle::optional<phi::DenseTensor> const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, int, int, int, phi::DenseTensor*)
4   void phi::funcs::ModulatedDeformableIm2col<float, phi::CPUContext>(phi::CPUContext const&, float const*, float const*, float const*, std::vector<long, std::allocator<long> > const&, std::vector<long, std::allocator<long> > const&, std::vector<long, std::allocator<long> > const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, int, float*)

----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1740236602 (unix time) try "date -d @1740236602" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x5ae21) received by PID 372349 (TID 0x7f7c5129e740) from PID 372257 ***]

I0222 15:04:08.187273 403073 init.cc:233] ENV [CUSTOM_DEVICE_ROOT]=/root/miniconda3/envs/bytetrack/lib/python3.10/site-packages/paddle_custom_device
I0222 15:04:08.187325 403073 init.cc:142] Try loading custom device libs from: [/root/miniconda3/envs/bytetrack/lib/python3.10/site-packages/paddle_custom_device]
sdaa plugin compiled with gcc
PaddlePaddle Compilation Commit: e5b01458d31bab831dbd96a53522bf207b2fcd9e
PaddlePaddle Compilation Version: 2.6.0
+---------+--------+---------------+--------------+-------------+----------+-----------+-----------+-------------+-------+---------------------+--------------------+
|         | paddle | paddle_commit | sdaa_runtime | sdaa_driver | teco_dnn | teco_blas | teco_tccl | teco_custom | sdpti | paddle_sdaa_version | paddle_sdaa_commit |
+---------+--------+---------------+--------------+-------------+----------+-----------+-----------+-------------+-------+---------------------+--------------------+
| Version | 2.6.0  | e5b0145       | 1.3.1        | 1.3.1       | 2.0.0b0  | 2.0.0b0   | 1.20.0    | 1.22.0      | 1.3.0 | 1.3.1               | 9671916            |
+---------+--------+---------------+--------------+-------------+----------+-----------+-----------+-------------+-------+---------------------+--------------------+
+--------------------------+---------------+---------------+
| Variable Name            | Default Value | Current Value |
+--------------------------+---------------+---------------+
| CUSTOM_DEVICE_BLACK_LIST |               |               |
+--------------------------+---------------+---------------+
| ENABLE_SDPTI             | 1             | 1             |
+--------------------------+---------------+---------------+
| HIGH_PERFORMANCE_CONV    | 0             | 0             |
+--------------------------+---------------+---------------+
| HIGH_PERFORMANCE_GEMM    | 0             | 0             |
+--------------------------+---------------+---------------+
| RANDOM_ALIGN_NV_DEVICE   |               |               |
+--------------------------+---------------+---------------+
| PADDLE_XCCL_BACKEND      |               | sdaa          |
+--------------------------+---------------+---------------+
| HIGH_PRECISION_OP_LIST   |               |               |
+--------------------------+---------------+---------------+
| FLAGS_sdaa_reuse_event   | true          | true          |
+--------------------------+---------------+---------------+
| FLAGS_sdaa_runtime_debug | false         | false         |
+--------------------------+---------------+---------------+
| FLAGS_sdaa_matmul_scale  | 1.0           | 1.0           |
+--------------------------+---------------+---------------+
| DUMP_INTO_PROFILER       | 0             | 0             |
+--------------------------+---------------+---------------+
I0222 15:04:08.265684 403073 custom_device.cc:1109] Successed in loading custom runtime in lib: /root/miniconda3/envs/bytetrack/lib/python3.10/site-packages/paddle_custom_device/libpaddle-sdaa.so
I0222 15:04:08.267675 403073 custom_kernel.cc:63] Successed in loading 271 custom kernel(s) from loaded lib(s), will be used like native ones.
I0222 15:04:08.267776 403073 init.cc:154] Finished in LoadCustomDevice with libs_path: [/root/miniconda3/envs/bytetrack/lib/python3.10/site-packages/paddle_custom_device]
I0222 15:04:08.267794 403073 init.cc:239] CustomDevice: sdaa, visible devices count: 1
Warning: Unable to use JDE/FairMOT/ByteTrack, please install lap, for example: `pip install lap`, see https://github.com/gatagat/lap
Warning: Unable to use numba in PP-Tracking, please install numba, for example(python3.7): `pip install numba==0.56.4`
2025-02-22 15:04:09,112 - DEBUG - matplotlib data path: /root/miniconda3/envs/bytetrack/lib/python3.10/site-packages/matplotlib/mpl-data
2025-02-22 15:04:09,117 - DEBUG - CONFIGDIR=/root/.config/matplotlib
2025-02-22 15:04:09,119 - DEBUG - interactive is False
2025-02-22 15:04:09,119 - DEBUG - platform is linux
2025-02-22 15:04:09,184 - DEBUG - CACHEDIR=/root/.cache/matplotlib
2025-02-22 15:04:09,185 - DEBUG - Using fontManager instance from /root/.cache/matplotlib/fontlist-v390.json
Warning: Unable to use numba in PP-Tracking, please install numba, for example(python3.7): `pip install numba==0.56.4`
Warning: Unable to use MOT metric, please install motmetrics, for example: `pip install motmetrics`, see https://github.com/longcw/py-motmetrics
Warning: Unable to use MCMOT metric, please install motmetrics, for example: `pip install motmetrics`, see https://github.com/longcw/py-motmetrics
Warning: import ppdet from source directory without installing, run 'python setup.py install' to install ppdet firstly
I0222 15:04:09.729333 403073 tcp_utils.cc:130] Successfully connected to 172.17.0.3:50289
2025-02-22 15:04:11,513 - DEBUG - Starting new HTTPS connection (1): paddledet.bj.bcebos.com:443
2025-02-22 15:04:11,673 - DEBUG - https://paddledet.bj.bcebos.com:443 "GET /models/mot/fairmot_dla34_30e_1088x608.pdparams HTTP/1.1" 200 130895015
2025-02-22 15:08:44,488 - INFO - Loss: 10.8979
2025-02-22 15:13:14,614 - INFO - Loss: 10.3049
2025-02-22 15:17:47,056 - INFO - Loss: 9.4932
2025-02-22 15:22:20,128 - INFO - Loss: 9.1844
2025-02-22 15:26:52,024 - INFO - Loss: 7.7717
2025-02-22 15:31:22,584 - INFO - Loss: 8.7069
2025-02-22 15:35:54,556 - INFO - Loss: 8.0085
2025-02-22 15:40:26,287 - INFO - Loss: 7.5734
2025-02-22 15:44:58,672 - INFO - Loss: 7.8066
2025-02-22 15:49:29,757 - INFO - Loss: 7.5940
2025-02-22 15:54:02,042 - INFO - Loss: 7.6938
2025-02-22 15:58:33,858 - INFO - Loss: 7.7223
2025-02-22 16:03:05,848 - INFO - Loss: 7.6598
2025-02-22 16:07:38,776 - INFO - Loss: 7.3613
2025-02-22 16:12:11,522 - INFO - Loss: 7.7426
2025-02-22 16:16:44,237 - INFO - Loss: 8.3191
2025-02-22 16:21:16,882 - INFO - Loss: 8.0546
2025-02-22 16:25:49,055 - INFO - Loss: 7.5681
2025-02-22 16:30:21,008 - INFO - Loss: 7.8347
2025-02-22 16:34:53,023 - INFO - Loss: 7.7365
2025-02-22 16:39:25,715 - INFO - Loss: 8.0385
2025-02-22 16:43:57,646 - INFO - Loss: 7.7155
2025-02-22 16:48:29,236 - INFO - Loss: 7.4955
2025-02-22 16:53:01,641 - INFO - Loss: 7.6386
2025-02-22 16:57:34,373 - INFO - Loss: 7.5226
2025-02-22 17:02:06,400 - INFO - Loss: 7.6433
2025-02-22 17:06:39,141 - INFO - Loss: 7.5499
2025-02-22 17:11:11,544 - INFO - Loss: 7.5726
2025-02-22 17:15:43,953 - INFO - Loss: 7.6119
2025-02-22 17:20:16,380 - INFO - Loss: 8.1728
2025-02-22 17:24:48,484 - INFO - Loss: 7.3159
2025-02-22 17:29:20,193 - INFO - Loss: 7.6541
2025-02-22 17:33:53,561 - INFO - Loss: 7.7750
2025-02-22 17:38:25,812 - INFO - Loss: 7.3466
2025-02-22 17:42:58,027 - INFO - Loss: 7.4976
2025-02-22 17:47:30,957 - INFO - Loss: 7.5894
2025-02-22 17:52:02,782 - INFO - Loss: 7.6417
2025-02-22 17:56:36,067 - INFO - Loss: 7.6439
2025-02-22 18:01:08,862 - INFO - Loss: 7.6915
2025-02-22 18:05:40,634 - INFO - Loss: 8.1486
2025-02-22 18:10:11,956 - INFO - Loss: 7.5004
2025-02-22 18:14:42,960 - INFO - Loss: 7.7147
2025-02-22 18:19:14,087 - INFO - Loss: 7.3897
2025-02-22 18:23:45,060 - INFO - Loss: 7.5927
2025-02-22 18:28:15,960 - INFO - Loss: 7.9884
2025-02-22 18:32:47,272 - INFO - Loss: 7.6984
2025-02-22 18:37:18,318 - INFO - Loss: 7.6260
2025-02-22 18:41:49,190 - INFO - Loss: 7.6084
2025-02-22 18:46:20,360 - INFO - Loss: 7.5834
